# Generated by Django 5.0.6 on 2024-12-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutfitPlanner', '0002_alter_category_options_clothes_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='stock',
        ),
        migrations.AddField(
            model_name='clothes',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='fabric',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
